# Generated by Django 5.2 on 2025-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField(default=0.0)),
                ("stok", models.IntegerField(default=0)),
                ("nombre", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
