# Generated by Django 5.2 on 2025-11-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_web_pcwl", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="stok",
        ),
        migrations.AddField(
            model_name="productos",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productos",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="productos",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productos",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productos",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de descuento (ej. 10.00 para 10%)",
                        max_digits=5,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocion",
                        to="my_web_pcwl.productos",
                    ),
                ),
            ],
        ),
    ]
