# Generated by Django 5.2.6 on 2025-12-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_pcwl', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
